[build]
  command = "node scripts/generate.js"
  publish = "."

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/pulpas/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
